sudo: required

services:
  - docker

script:
  - |
    set -e
    for path in `find . -name Dockerfile`; do
        echo $path
        docker run --rm -i lukasmartinelli/hadolint < $path
    done
  - build.sh
  - push.sh